import { useEffect, useRef, useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { useRemote } from '@/hooks/useRemote';
import { getFund } from '@/utils/fundApi';
import { localDate } from '@/utils/fundFormatting';
import { useFundStore } from '@/stores/fund';
import { BackLink, Button, ErrorState, Loading, Modal, Notice, PageHeader, Panel, WriteButton } from '@/components/ui';
export default function FundForm({id}:{id?:number}){
  const navigate=useNavigate(),pending=useRef(false);
  const result=useRemote(signal=>id?getFund(id,signal):Promise.resolve(null),[id]);
  const [name,setName]=useState(''),[date,setDate]=useState(localDate()),[currency,setCurrency]=useState<'CNY'|'USD'>('CNY'),[tags,setTags]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false),[confirmDelete,setConfirmDelete]=useState(false),[deleteName,setDeleteName]=useState('');
  useEffect(()=>{if(result.data){setName(result.data.name);setDate(result.data.start_date);setCurrency(result.data.currency);setTags(result.data.tags||'');}},[result.data]);
  const submit=async(event:React.FormEvent)=>{event.preventDefault();if(pending.current)return;pending.current=true;setBusy(true);setError('');try{const data={name:name.trim(),start_date:date,currency,tags};if(id)await useFundStore.getState().updateFund(id,data);else await useFundStore.getState().createFund(data);navigate(id?'/funds/'+id:'/funds');}catch(e){setError(e instanceof Error?e.message:'保存失败');}finally{pending.current=false;setBusy(false);}};
  const remove=async()=>{if(!id||pending.current||deleteName!==result.data?.name)return;pending.current=true;setBusy(true);setError('');try{await useFundStore.getState().deleteFund(id);navigate('/funds');}catch(e){setError(e instanceof Error?e.message:'删除失败');}finally{pending.current=false;setBusy(false);}};
  if(result.loading)return <Loading/>;if(result.error)return <ErrorState error={result.error} retry={result.reload}/>;
  return <><BackLink to={id?'/funds/'+id:'/funds'}/><PageHeader title={id?'编辑基金':'新建基金'} description="基本信息与现有账务记录分开管理，保持数据口径清晰。"/><div className="form-layout"><Panel title="基金信息" className="panel-pad"><form onSubmit={submit}><fieldset disabled={busy}>{error&&!confirmDelete&&<Notice tone="error">{error}</Notice>}<label className="field">基金名称<input name="fund-name" required maxLength={100} value={name} onChange={e=>setName(e.target.value)} placeholder="例如：长期配置组合" autoFocus/></label><div className="form-row"><label className="field">成立日期<input name="start-date" type="date" required value={date} onChange={e=>setDate(e.target.value)}/></label><label className="field">记账币种<select name="currency" value={currency} onChange={e=>setCurrency(e.target.value as 'CNY'|'USD')}><option value="CNY">人民币 CNY</option><option value="USD">美元 USD</option></select></label></div><label className="field">基金标签<input name="tags" value={tags} maxLength={500} onChange={e=>setTags(e.target.value)} placeholder="多个标签使用英文逗号分隔"/><span className="field-hint">用于列表与总览筛选，不影响资产计算。</span></label>{id&&currency!==result.data?.currency&&<Notice tone="warning">更改币种只修改记账标识，不会自动换汇或重算历史金额。请确认这确实是原币种信息更正。</Notice>}<div className="form-actions"><Button onClick={()=>navigate(id?'/funds/'+id:'/funds')}>取消</Button><WriteButton variant="primary" type="submit" disabled={busy}>{busy?'正在保存…':id?'保存修改':'创建基金'}</WriteButton></div></fieldset></form></Panel><aside><Panel title="记录说明" className="panel-pad"><p className="muted">基金从初始净值 1 开始。添加投资者并记录申购后，可更新净值与查看历史曲线。</p><p className="footnote">成立日期与操作的记账日期独立；编辑基本信息不会重排操作历史。</p></Panel>{id&&<Panel title="危险操作" className="panel-pad danger-zone"><p>删除将移除基金及其投资者、持仓、净值和操作历史，无法在页面内撤销。</p><WriteButton variant="danger" onClick={()=>{setError('');setDeleteName('');setConfirmDelete(true);}}>删除基金</WriteButton></Panel>}</aside></div>
    {confirmDelete&&<Modal title="确认删除基金" description="此操作会永久删除相关记录。建议先导出备份。" onClose={()=>setConfirmDelete(false)} busy={busy} footer={<><Button disabled={busy} onClick={()=>setConfirmDelete(false)}>取消</Button><WriteButton variant="danger" disabled={busy||deleteName!==result.data?.name} onClick={remove}>{busy?'正在删除…':'永久删除'}</WriteButton></>}><Notice tone="warning">即将删除：{result.data?.name}</Notice>{error&&<Notice tone="error">{error}</Notice>}<label className="field">输入基金完整名称以确认<input autoFocus name="delete-fund-name" value={deleteName} onChange={e=>setDeleteName(e.target.value)}/></label></Modal>}
  </>;
}
