import fs from 'node:fs';
import {execFileSync} from 'node:child_process';
import {assert,connect,api,ready,tap,setValue,state,screenshotRoot} from './helpers.mjs';

const b=await connect('editor'),s=state(),checks=[];
const downloadPath=fs.mkdtempSync('/private/tmp/fund-ui-downloads-');
const getFunds=async()=> (await api(b,'/api/v1/funds?page_size=100')).data.data.items;
const submitImport=async()=> {
  await tap(b,'核对并导入');
  await b.wait("Boolean(document.querySelector('dialog[open]'))");
  await tap(b,'确认导入','dialog');
};
try {
  await b.navigate('http://localhost:20260/funds/'+s.fundId);
  await ready(b,s.name);
  await b.call('Browser.setDownloadBehavior',{behavior:'allow',downloadPath,browserContextId:b.contextId,eventsEnabled:true});
  await tap(b,'导出完整记录');
  const jsonlDeadline=Date.now()+15000;
  while(!b.events.some(e=>e.method==='Browser.downloadProgress'&&e.params.state==='completed')) {
    if(Date.now()>jsonlDeadline)throw new Error('JSONL download did not finish');
    await new Promise(resolve=>setTimeout(resolve,100));
  }
  const original=(await api(b,'/api/v1/funds/'+s.fundId)).data.data;
  const exported=await b.evaluate("fetch('/api/v1/funds/"+s.fundId+"/operations/export').then(r=>r.text())");
  const rows=exported.trim().split('\n').map(l=>JSON.parse(l));
  assert.equal(rows[0]._type,'fund_meta');
  assert.ok(fs.readFileSync(downloadPath+'/fund_'+s.fundId+'_operations.jsonl','utf8').includes('fund_meta'));
  checks.push('real JSONL download contains metadata and operation history');
  const cloneName='UI 回放 · JSONL '+Date.now();
  const clone=[{...rows[0],name:cloneName},...rows.slice(1)].map(r=>JSON.stringify(r)).join('\n');
  await b.navigate('http://localhost:20260/data');
  await ready(b,'导入与导出');
  await b.fill('textarea[name="import-content"]',clone);
  await submitImport();
  await b.wait("!document.querySelector('dialog[open]') && document.body.innerText.includes('导入完成')");
  const cloned=(await getFunds()).find(f=>f.name===cloneName);
  assert.ok(cloned);
  for(const key of ['balance','total_share','net_asset_value','currency','start_date'])assert.equal(cloned[key],original[key]);
  checks.push('JSONL UI import replays unchanged balances, shares, NAV, currency and start date');
  const badName='失败导入不应留存';
  const invalidOp={...rows.find(r=>r.operation_type==='invest'),amount:-1};
  const bad=[{...rows[0],name:badName},...rows.slice(1),invalidOp].map(r=>JSON.stringify(r)).join('\n');
  await b.fill('textarea[name="import-content"]',bad);
  await submitImport();
  await b.wait("Boolean(document.querySelector('dialog [role=alert]'))");
  assert.ok(!(await getFunds()).some(f=>f.name===badName));
  assert.ok(await b.evaluate("document.querySelector('textarea[name=import-content]').value.includes('失败导入不应留存')"));
  checks.push('failed import keeps input and leaves no partially created fund');
  await tap(b,'返回核对','dialog');
  await b.navigate('http://localhost:20260/funds/'+s.fundId+'/data');
  await ready(b,'导入与导出');
  const append=[rows[0],{...rows.find(r=>r.operation_type==='invest'),amount:13,operation_date:'2026-09-05'}].map(r=>JSON.stringify(r)).join('\n');
  await b.fill('textarea[name="import-content"]',append);
  await submitImport();
  await b.wait("!document.querySelector('dialog[open]') && document.body.innerText.includes('导入完成')");
  const appended=(await api(b,'/api/v1/funds/'+s.fundId)).data.data;
  const importedShares=Number((13/rows.find(r=>r.operation_type==='invest').nav_at_op).toFixed(6));
  assert.ok(Math.abs(appended.balance-(original.balance+importedShares*original.net_asset_value))<0.000001);
  assert.ok(Math.abs(appended.total_share-(original.total_share+importedShares))<0.000001);
  assert.equal(appended.net_asset_value,original.net_asset_value);
  checks.push('append import preserves historical nav_at_op and changes only the selected fund');
  const temp=fs.mkdtempSync('/private/tmp/fund-ui-zip-');
  fs.writeFileSync(temp+'/good.jsonl',[{...rows[0],name:'UI ZIP · 美元组合',currency:'USD'},...rows.slice(1)].map(r=>JSON.stringify(r)).join('\n'));
  fs.writeFileSync(temp+'/bad.jsonl',bad);
  execFileSync('/usr/bin/zip',['-q','fixture.zip','good.jsonl','bad.jsonl'],{cwd:temp});
  await b.navigate('http://localhost:20260/data');
  await ready(b,'导入与导出');
  const {root}=await b.send('DOM.getDocument');
  const {nodeId}=await b.send('DOM.querySelector',{nodeId:root.nodeId,selector:'input[name="import-file"]'});
  await b.send('DOM.setFileInputFiles',{nodeId,files:[temp+'/fixture.zip']});
  await b.wait("document.body.innerText.includes('fixture.zip') && !document.body.innerText.includes('正在读取')");
  await submitImport();
  await b.wait("!document.querySelector('dialog[open]') && document.body.innerText.includes('个文件失败')");
  const zipPage=(await b.snapshot()).text;
  assert.ok(zipPage.includes('1 个基金导入成功，1 个文件失败'));
  const all=await getFunds();
  assert.ok(all.some(f=>f.name==='UI ZIP · 美元组合'&&f.currency==='USD'));
  assert.ok(!all.some(f=>f.name===badName));
  checks.push('real ZIP file upload reports independent success and rollback per file');
  const completedBeforeZip=b.events.filter(e=>e.method==='Browser.downloadProgress'&&e.params.state==='completed').length;
  await setValue(b,'select[name="export-fund"]','');
  await tap(b,'导出 ZIP');
  const until=Date.now()+15000;
  while(b.events.filter(e=>e.method==='Browser.downloadProgress'&&e.params.state==='completed').length<=completedBeforeZip) {
    if(Date.now()>until)throw new Error('ZIP download did not finish');
    await new Promise(resolve=>setTimeout(resolve,100));
  }
  const zip=fs.readdirSync(downloadPath).find(name=>name.endsWith('.zip'));
  assert.ok(zip&&fs.readFileSync(downloadPath+'/'+zip).subarray(0,2).equals(Buffer.from('PK')));
  checks.push('real batch ZIP export completes with valid ZIP signature');
  await b.navigate('http://localhost:20260/funds/'+cloned.id+'/edit');
  await ready(b,'编辑基金');
  await b.fill('input[name="tags"]','UI回归,已核对');
  await setValue(b,'input[name="start-date"]','2026-08-31');
  await tap(b,'保存修改');
  await ready(b,cloneName);
  const edited=(await api(b,'/api/v1/funds/'+cloned.id)).data.data;
  assert.equal(edited.start_date,'2026-08-31');
  assert.equal(edited.tags,'UI回归,已核对');
  assert.equal(edited.balance,original.balance);
  checks.push('metadata edit preserves accounting and selected date');
  await b.navigate('http://localhost:20260/funds/'+cloned.id+'/edit');
  await ready(b,'编辑基金');
  await tap(b,'删除基金');
  await b.wait("Boolean(document.querySelector('input[name=delete-fund-name]'))");
  assert.ok((await b.snapshot()).controls.some(c=>c.text==='永久删除'&&c.disabled));
  await b.fill('input[name="delete-fund-name"]',cloneName);
  await tap(b,'永久删除','dialog');
  await ready(b,'基金列表');
  assert.equal((await api(b,'/api/v1/funds/'+cloned.id)).status,404);
  assert.equal((await api(b,'/api/v1/funds/'+s.fundId)).status,200);
  checks.push('typed-name deletion removes only this disposable replay fixture');
  console.log(JSON.stringify({passed:checks.length,checks}));
}catch(error){
  await b.screenshot(screenshotRoot+'failure-data.png',1440,1100);
  console.error(error.stack);
  console.log(JSON.stringify(await b.snapshot()));
  process.exitCode=1;
}finally{b.close();}
